### ISSUE TITLE
Problems with autorenewable subscriptions

### ISSUE THREAD

**Issue by ElinaBS** [Telerik-Verified-Plugins/InAppPurchase#4]
Hi! 

We would like to use your plugin for our app that uses auto-renewable subscriptions. We have managed to make the first purchase work, but we cannot get the receipt information for the renewals later on when doing refresh(). Only a list of transaction IDs are returned, but no info on the billing cycle or expiration date is retrieved. Is this missing from the plugin or are we missing something? 

Thank you for your help,
Elina, CTO and co-founder of Natural Cycles

**Comment by EddyVerbruggen** [comment]
Hi @ElinaBS can you please ask this questin at the upstream repository as there are more folks watching it, so you're more likely to get a useful response?
